### ISSUE TITLE
Storage Poll too frequent

### ISSUE THREAD

**Issue by dhughes76227** [dchesterton/amcrest2mqtt#22]
interval is set near the top 
storage_sensors_interval = 60  # 1 hour

and used in the timer start
    Timer(storage_sensors_interval, refresh_storage_sensors).start()

Interval should be expressed in seconds instead of minutes.  1 hour would be 3600.

I changed a copy to 86400 because I only wanted it once a day.

Nice script by the way.  
FYI, I have the AD410 but also have some other dahua cameras.  I added support for defining the events through the environment and support for smart motion detection for human and vehicle for other cameras.  Easy to follow and modify.

**Comment by Mark612** [comment]
Would be nice to have an environment variable that changes the storage poll to whatever time as you mention, but also 0. Seems I don't have any storage in my doorbell, so I get this error constantly.



27/06/2021 18:45:13 [INFO] Fetching storage sensors...,
<Front Door:Z0500E4BC6288> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.20.133:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo'),
<Front Door:Z0500E4BC6288> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.20.133:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo'),

**Comment by dchesterton** [comment]
Thanks for your comments. I've created a new `STORAGE_POLL_INTERVAL` environment variable to control how often it polls and set it to 3600 (1 hour) by default.

**Comment by dchesterton** [comment]
@dhughes76227 if you were happy to contribute your code for smart human/vehicle detection I'd be keen to implement it :)
